outscale/packetgraph

vtep/src/vtep.c

vtep: fix style vtep.c

---

.travis.yml

ci: fix travis build to take the right branch

---

.travis.yml

ci: fix travis environement configuration

---

.travis.yml

ci: remove unused lib

---

README.md

doc: update README.md with new images

---

.travis.yml
Makefile.am
README.md
examples/rxtx/README.md
examples/rxtx/run.sh
examples/rxtx/rxtx.c
include/packetgraph/packetgraph.h
include/packetgraph/rxtx.h
src/rxtx.c
tests/rxtx/bench-rxtx.c
tests/rxtx/bench.c
tests/rxtx/bench.sh
tests/rxtx/test.sh
tests/rxtx/tests.c

ci: add non-qemu based benchmarks

---

.travis.yml

ci: enable lizard test

---

src/vtep.c

vtep: fix segv in decapsulate_simple

---

include/packetgraph/print.h
src/print.c
tests/print/tests.c

print: avoid double fclose

---

src/vtep.c

vtep: fix leak in multicast_internal

---

tests/rxtx/tests.c

Signed-off-by: Tarrade Nicolas <nicolas.tarrade@outscale.com>

rxtx: test empty burst don't propagate

---

tests/antispoof/bench-antispoof.c
tests/core/bench-nop.c
tests/diode/bench-diode.c
tests/firewall/bench-firewall.c
tests/nic/bench-nic.c
tests/print/bench-print.c
tests/queue/bench-queue.c
tests/rxtx/bench-rxtx.c
tests/switch/bench-switch.c

bench: remove useless sizeof

---

.travis.yml
README.md

packetgraph: upgrade dpdk to 16.11

---

src/packets.c
src/packets.h
src/switch.c
src/vtep.c

packetgraph: clean useless includes

---

.travis.yml

build: remove trailling whitespace

---

README.md

user-dipole: add description in readme

---

src/tap.c

tap: remove select

---

.travis.yml

build: update dpdk in travis

---

Makefile.am

build: fix clang unknow option with asan

---

tests/firewall/tests.c

tests: fix overflow in firewall test

---

tests/vhost/bench.sh

tests: allow tests with only one hugepage

---

README.md

README.md: change read by ready

---

.travis.yml
README.md
src/brick-int.h
src/nic.c

nic: update dpdk v19.02

---

src/thread.c

thread: fix clang static analizer check

---

build_jenkins

build: add script for jenkins build

---

build_jenkins

build: fix checking error

---

.gitmodules
src/firewall.c

change libqsbr fork for initial project, update npf and firewall.c

3rdparty: update libqsbr

---

doc/check_error.sh
doc/deploy_documentation.sh
doc/sed_readme.sh
dpdk_symbols.sh
error_print.sh
examples/dperf/run.sh
examples/firewall/run.sh
examples/nic/run.sh
examples/rxtx/run.sh
examples/switch/run.sh
examples/switch/run_vhost.sh
tests/antispoof/bench.sh
tests/core/bench.sh
tests/diode/bench.sh
tests/firewall/bench.sh
tests/integration/test.sh
tests/ip-fragment/bench.sh
tests/nic/bench.sh
tests/pmtud/bench.sh
tests/print/bench.sh
tests/queue/bench.sh
tests/rxtx/bench.sh
tests/style/test.sh
tests/switch/bench.sh
tests/tap/bench.sh
tests/vhost/bench.sh
tests/vhost/test.sh
tests/vtep/bench.sh

Signed-off-by: Axel Viau <axel.viau@outscale.com>

script: fixing shell errors for shellcheck

---

src/nic.c

nic: update packetgraph using dpdk_v18.05_to_v19.02

---

npfmakefile.am
src/firewall.c
tests/firewall/tests.c

and remove rogue printf
This need to be tested by asan, I was lazy to do this,
so don't merge yet.
But you fell in a testing mood, you can check that this work with asan.

3rdparty: update npf

---

Makefile
configure

- add --prefix to configure in order to configure install dir
- add "make install" option
- add "make uninstall" option

build: add install/uninstall

---

.travis.yml
tests_travis/bench_all.sh
tests_travis/doc_style.sh
tests_travis/test_all.sh

Signed-off-by: Axel Viau <axel.viau@outscale.com>

travis: DPDK cache and tests parallelization

---

.travis.yml
README.md

pg: we don't need libtool and automake anymore

---

build_jenkins
run_tests.sh

build: small fix

---

src/nic.c

nic: update nic to fix leak memory

---

.travis.yml

travis: fix rat install

---

.travis.yml

travis: remove rat package

---

Makefile
build_jenkins
configure
run_tests.sh
tests_coverage.sh

build: enable coverage tests

---

.travis.yml

Signed-off-by: William Nizard <william.nizard@outscale.com>

travis : update script for ubuntu 18.4

---

.travis.yml

travis: use apt instead of apt-get

---

npf.mk
src/firewall.c

Npf update

---

README.md
src/tap.c

tap: add option to ignore some errors

---

include/packetgraph/antispoof.h
src/antispoof.c

Signed-off-by: hanen mizouni <hanen.mizouni@outscale.com>

antispoof: add defines for NDP and ARP

---

tests_travis/doc_style.sh

travis: install system doxygen

---

Makefile
README.md
benchmark.mk
configure
include/packetgraph/accumulator.h
include/packetgraph/packetgraph.h
run_tests.sh
src/accumulator.c
tests.mk
tests/accumulator/bench.c
tests/accumulator/bench.sh
tests/accumulator/test.sh
tests/accumulator/tests.c

update accumulator brick by Gaspard and New PR :)

Accumulator

---

src/brick-int.h
src/brick.c

Signed-off-by: hanen mizouni <hanen.mizouni@outscale.com>

brick:correct return type

---

include/packetgraph/packet.h

Signed-off-by: Cloud User <matthias.gatto@outscale.com>

common: add informations about pg_packets_t

---

run_tests.sh
tests.mk

build: fix udp-filter test

---

.travis.yml
include/packetgraph/brick.h
src/brick.c
src/npf/libcdb/src/cdbr.c
src/tap.c
src/utils/errors.h
src/utils/mac-table.h
src/vtep.c

that's mostly NULL check.
Some might be false positive.

Fix gcc -fsanitazer errors

---

src/packets.c
src/packets.h
tests/vtep/tests.c

tests: fix packets bug in vtep tests
